spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1
        - id: cart
          uri: lb://cart
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
        - id: food
          uri: lb://food
          predicates:
            - Path=/food/**
          filters:
            - StripPrefix=1
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: deliveryaddress
          uri: lb://deliveryaddress
          predicates:
            - Path=/deliveryaddress/**
          filters:
            - StripPrefix=1
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
